server:
  port: 8080

spring:
  data:
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    mongodb:
      host: localhost
      port: 27017
      database: turtledream
logging:
  level:
    com.example.turtledreambackend: DEBUG  # 패키지별 로그 레벨 설정
    root: INFO  # 전체 로그 레벨 설정